### ISSUE TITLE
Tripal Fields

### ISSUE THREAD

**Issue by 4ctrl-alt-del** [tripal/t4d8#129]
This is a super thread issue that I will use to gather all information and feedback concerning my efforts to upgrade Tripal terms and fields to Drupal 8/9. Because of the extreme difference between Drupal 7 and 8 and Drupal's decision to move all storage related tasks to the entity level, this is basically a complete rework of Tripal fields.

**Comment by 4ctrl-alt-del** [comment]
Created root branch for all work related to this upgrade named ~~129-Tripal4VTF~~ 129-TripalFields.

**Comment by 4ctrl-alt-del** [comment]
The general plan for progress is the following:

1. Add tripal vocabulary plugin
2. Add tripal term typed data and definitions
3. Add tripal storage plugin
4. Add tripal schema plugin
3. Add tripal field that works with tripal vocabulary terms, storage, and schema.
4. Add tripal entity that works with tripal vocabulary terms, sotrage, and schema.
5. Add tripal entity storage that works with tripal entities.
6. Add tripal entity schema that works with tripal entitites.

This plan could change dramatically as work progresses over the months but hopefully it stays the same.

I am currently between steps 1 and 2.

**Comment by Ferrisx4** [comment]
Closing the 129-TripalFields-vocabRabbitHole branch in favor of smaller, more manageable branches. Patch included here for all work done, saved with txt extension so Github would allow an upload.

[129-TripalFields-vocabRabbitHole.patch.txt](https://github.com/tripal/t4d8/files/8162391/129-TripalFields-vocabRabbitHole.patch.txt)

**Comment by laceysanderson** [comment]
Moving the Tripal Vocab design documentation out of pending and integrating it with the rest of the documentation.

I'm saving the following here as it needs to be re-worked a bit and integrated into the developer docs:

```rst
Terms can be retrieved by

1. Using the Tripal Vocabulary Manager to search terms by name within a vocabulary.
2. Using the Tripal ID Space Manager to search terms by name or accession within an ID Space.
3. Using the Tripal ID Space Manager to get parent or child terms of an existing term.
4. Using the static TripalTerm::suggestTerms method to search by name across vocabularies and ID spaces.
    
.. table:: Ways to search for TripalTerms

	+------------------+----------------+------------+-----------------+----------+-------------+
	| Class            | Method         | Return     | Search Property | IDSpace* | Vocabulary* |
	+==================+================+============+=================+==========+=============+
	| TripalTerm       | suggestTerms+  | array      | name            | No       | No          |
	+------------------+----------------+------------+-----------------+----------+-------------+
	| TripalVocabulary | getTerms       | array      | name            | No       | Yes         |
	+------------------+----------------+------------+-----------------+----------+-------------+
	| TripalIdSpace    | getTerms       | array      | name            | Yes      | Yes         |
	+------------------+----------------+------------+-----------------+----------+-------------+
	| TripalIdSpace    | getTerm        | TripalTerm | accession       | Yes      | Yes         |
	+------------------+----------------+------------+-----------------+----------+-------------+
	| TripalIdSpace    | getParent      | TripalTerm | TripalTerm      | Yes      | Yes         |
	+------------------+----------------+------------+-----------------+----------+-------------+
	| TripalIdSpace    | getChildren    | array      | TripalTerm      | Yes      | Yes         |
	+------------------+----------------+------------+-----------------+----------+-------------+

| *\* These two columns indicate information which is required for the search.*
| *\+ This is a static method of TripalTerm.*
```

**Comment by laceysanderson** [comment]
Moving the Vocab todo list here for better expansion, etc. @Ferrisx4 

The following is completed:

- Create Vocabulary + ID Space Plugin definitions
- Create plugin managers and ensure plugins are discoverable
- Design TripalTerm class
- Design interfaces for Vocabulary and ID Space plugins
- Stub out base classes

And the remaining tasks:

- [x] Fill in base method functionality based on the stub. Specifically, see ``tripal/src/TripalVocabTerms/TripalVocabularyBase.php`` and ``tripal/src/TripalVocabTerms/TripalIdSpaceBase.php``
- [x] Fill in method functionality for TripalTerm class (``tripal/src/TripalVocabTerms/TripalTerm.php``). There should be no database access in these methods. For example, the TripalTerm->getIdSpaceObject method should use the id space name associated with the term and the IdSpace plugin manager to retrieve the object.
- [x] Create a core implementation (or two). We will definitely want a Chado-focused implementation that takes into account there may be multiple Chado schema. Additionally, we may want a Tripal implementation with its own storage tables to overcome some limitations in Chado. More discussion within the community is needed.
- [x] Remove the old entity-based implementation of vocabulary, ID Spaces, Terms
- [x] Switch Chado prepare to use new vocabularies?
- [x] Switch current entities to use new vocab design?

**Comment by spficklin** [comment]
The remaining tasks in @laceysanderson checklist are completed. I think this can be closed.
