### ISSUE TITLE
Discussion question: Should uninstalling tripal_chado module drop chado?

### ISSUE THREAD

**Issue by risharde** [tripal/t4d8#142]
As much as this might be an obvious answer, I just realized that this might not be good for live sites (safety). Admins should in theory be aware of this (like either we give them an are you sure option or just leave chado be!) (I vaguely recalled that in Tripal 3, we tried not to delete chado data) but testing on Tripal 4, the uninstall works ie.deletes the chado tables! What do you guys think about this?

@spficklin @laceysanderson @Ferrisx4 @4ctrl-alt-del

**Comment by laceysanderson** [comment]
Oh! I don't think that is intended functionality... uninstalling Tripal Chado should leave Chado alone IMO. We can explore whether we think it should remove custom tables with an obvious warning... and it should remove any management tripal tables added to the Drupal schema... but not Chado.

**Comment by risharde** [comment]
Thank you @laceysanderson for the feedback! I will try to remember to look into this further since this might be an easy fix hopefully soon but I'm refocusing my effort on better PRs for importer code for you :)

**Comment by spficklin** [comment]
I agree with @laceysanderson. In Tripal v3 nothing in Chado is ever removed on an uninstall of Chado, including custom tables. I think we should keep it that way.   Drupal would automatically remove any of our management Tripal tables

**Comment by guignonv** [comment]
Agreed as well. Uninstalling tripal_chado module should not touch anything in chado schema (but could in Drupal "public" schema).

**Comment by laceysanderson** [comment]
I just tested this on the most recent version and uninstalling tripal_chado doesn't remove any Chado tables.
