### ISSUE TITLE
Multi-chado Design Documentation

### ISSUE THREAD

**Issue by spficklin** [tripal/t4d8#143]
@laceysanderson and @guignon We need some design documentation for how the multi-Chado is going to work in Tripal 4.  @risharde is working on custom tables and functional testing which needs to know where tables are located and we need to know how to alter API functions to support multi-chado.

This issue is a note that it needs to be added

**Comment by laceysanderson** [comment]
Yes, this is on my radar :-) In the meantime, you can see the current available documentation in the original PR: https://github.com/tripal/t4d8/pull/131

**Comment by guignonv** [comment]
Passing by more than a month later but the doc is there:
https://tripal4.readthedocs.io/en/latest/design/pending/biodb.html
Should we close this issue?

**Comment by laceysanderson** [comment]
Yes, I believe we close this issue :-)
