### ISSUE TITLE
Interface is a reserved word

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/t4d8#178]
https://github.com/tripal/t4d8/blob/8d8fd93aee418c320d626c5efc273625718c2369/tripal/src/TripalVocabTerms/TripalVocabularyBase.php#L6

The preceding line violates PHP's rule about using reserved words, in this case Interface, in namespaces.
We will have to change the directory name and any references to files in that directory. Suggested by the Stackoverflow answer below, we can simply pluralize Interface to Interfaces to get around this rule for minimal change.

Sources:
https://www.php.net/manual/en/reserved.keywords.php
https://stackoverflow.com/a/44225572

**Comment by laceysanderson** [comment]
Ooops! I like the pluralized option although we will have to do it for all the directories in TripalVocabTerms for consistency. I say go for it @Ferrisx4 and submit a PR -it's a small enough change I don't think it needs a big discussion. :-)

**Comment by Ferrisx4** [comment]
There is at least one more instance of references to the old naming schema, reopening.
