### ISSUE TITLE
Group 1: Upgrade Tripal Core blocks

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#18]
Blocks to be upgraded:
- Notifications
![Screen Shot 2020-01-05 at 1 12 14 PM](https://user-images.githubusercontent.com/1566301/71784797-24be5800-2fbd-11ea-9ad0-60c6f6ed841b.png)
- Powered by Tripal
![Screen Shot 2020-01-05 at 1 13 11 PM](https://user-images.githubusercontent.com/1566301/71784798-2a1ba280-2fbd-11ea-8ceb-d20ae2e93e5a.png)
- Content bar chart
![Screen Shot 2020-01-05 at 1 12 23 PM](https://user-images.githubusercontent.com/1566301/71784799-2d169300-2fbd-11ea-855c-540a81d748b4.png)

Resources:
- [Drupal 8 Block tutorial](https://www.drupal.org/docs/8/creating-custom-modules/creating-custom-blocks/create-a-custom-block)
- [Changelog: blocks are now plugins](https://www.drupal.org/node/1880620)
- [Definition in Tripal 3](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/tripal.module#L1130-L1358)

**Comment by par12005** [comment]
I am waiting to mark my PR tripal/t4d8#43 as "ready to merge" because I would like to have the `tripal_admin_notfications` table spelled correctly (PR tripal/t4d8#42) before this code is merged, since the Notifications block depends on that table.

**Comment by par12005** [comment]
Also, the "Dismiss notification" links are valid but currently do nothing, because I wasn't sure if they would count towards this issue. If so, I will implement their functionality and add it to PR tripal/t4d8#43 as well.

**Comment by laceysanderson** [comment]
Moved notifications functionality into tripal/tripal#1331. Now this issue can be closed -Thank you @par12005!
