### ISSUE TITLE
Updates to Chado\Storage

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#2]
Please tag all tickets and pr's with group 2 to denote it relates to this group of updates.

Files this update will require to be reviewed and updated (in order):

- [ ] Tripal Chado Module
    - [x] Convert tripal_chado.info to tripal_chado.yml
        - [ ]  tripal_chado.module
    - [ ] Convert hook_menu and forms
    - [ ] Convert D7 variables to D8 Config
    - [ ] Convert D7 variables to D8’s state system
    - [ ] tripal_chado.install
    - [ ] includes
        - [ ] api
            - [ ] ChadoRecord.inc
            - [x] ChadoSchema.inc
            - [x] generate_chado_schema_file.php
            - [ ] Modules
                - [ ] tripal_chado.analysis.api.inc
                - [ ] tripal_chado.contact.api.inc
                - [x] tripal_chado.cv.api.inc
                - [x] tripal_chado.db.api.inc
                - [ ] tripal_chado.feature.api.inc
                - [ ] tripal_chado.organism.api.inc
                - [ ] tripal_chado.phylotree.api.inc
                - [ ] tripal_chado.project.api.inc
                - [ ] tripal_chado.pub.api.inc
                - [ ] tripal_chado.stock.api.inc
            - [ ] tripal_chado.api.inc
            - [x] tripal_chado.custom_tables.api.inc
            - [ ] tripal_chado.entity.api.inc
            - [ ] tripal_chado.migrate.api.inc
            - [ ] tripal_chado.mviews.api.inc
            - [ ] tripal_chado.property.api.inc
            - [x] tripal_chado.query.api.inc
            - [x] tripal_chado.schema_v1.2.api.inc
            - [x] tripal_chado.schema_v1.3.api.inc
            - [x] tripal_chado.schema_v1.11.api.inc
            - [x] tripal_chado.schema.api.inc
            - [ ] tripal_chado.semweb.api.inc
            - [x] tripal_chado.variables.api.inc
        - [ ] ChadoDatabaseConnection.inc
        - [ ] setup
            - [ ] tripal_chado.chado_v1_1.inc
            - [ ] tripal_chado.chado_v1.2.inc
            - [ ] tripal_chado.chado_vx_x.inc
            - [ ] Tripal_chado.setup.inc
        - [ ] tripal_chado.bundle.inc
        - [ ] tripal_chado.custom_tables.inc
        - [ ] tripal_chado.cv.inc
        - [ ] tripal_chado.db.inc
        - [ ] tripal_chado.entity.inc
        - [ ] tripal_chado.field_storage.inc
        - [ ] tripal_chado.fields.inc
        - [ ] tripal_chado.install.inc
        - [ ] tripal_chado.mapping.inc
        - [ ] tripal_chado.migrate.inc
        - [ ] tripal_chado.mviews.inc
        - [ ] tripal_chado.phylotree.inc
        - [ ] tripal_chado.pub_search.inc
        - [ ] tripal_chado.publish.inc
        - [ ] tripal_chado.schema.inc
        - [ ] tripal_chado.semweb.inc
        - [ ] tripal_chado.seq_extract.inc
        - [x] Tripal_chado.vocab_storage.inc
    - [ ] tripalfields
        - [ ] chadofield.inc
        - [ ] chadofieldformatter.inc
        - [ ] chadofieldwidget.inc
        - [ ] chado_linker__contact
            - [ ] chado_linker__contact_formatter.inc
            - [ ] chado_linker__contact_widget.inc
            - [ ] Chado_linker__contact.inc
        - [ ] Chado_linker__prop
            - [ ] chado_linker__prop_formatter.inc
            - [ ] chado_linker__prop_widget.inc
            - [ ] chado_linker__prop.inc
        - [ ] data__accession
            - [ ] data__accession_formatter.inc
            - [ ] data__accession_widget.inc
            - [ ] Data__accession.inc
        - [ ] data__protein_sequence
            - [ ] data__protein_sequence_formatter.inc
            - [ ] data__protein_sequence_widget.inc
            - [ ] Data__protein_sequence.inc
        - [ ] data__sequence
            - [ ] data__sequence_formatter.inc
            - [ ] data__sequence_widget.inc
            - [ ] Data__sequence.inc
        - [ ] data__sequence_checksum
            - [ ] data__sequence_checksum_formatter.inc
            - [ ] data__sequence_checksum_widget.inc
            - [ ] Data__sequence_checksum.inc
        - [ ] Data__sequence_coordinates
            - [ ] data__sequence_coordinates_formatter.inc
            - [ ] data__sequence_coordinates_widget.inc
            - [ ] data__sequence_coordinates.inc
        - [ ] Data__sequence_coordinates_table
            - [ ] data__sequence_coordinates_table_formatter.inc
        - [ ] data__sequence_length
            - [ ] data__sequence_length_formatter.inc
            - [ ] data__sequence_length_widget.inc
            - [ ] Data__sequence_length.inc
        - [ ] efo__array_design
            - [ ] efo__array_design_formatter.inc
            - [ ] efo__array_design_widget.inc
            - [ ] Efo__array_design.inc
        - [ ] Go__gene_expression
            - [ ] go__gene_expression_formatter.inc
            - [ ] go__gene_expression_widget.inc
            - [ ] go__gene_expression.inc
        - [ ] Local__contact
            - [ ] local__contact_formatter.inc
            - [ ] local__contact_widget.inc
            - [ ] local__contact.inc
        - [ ] Local__source_data
            - [ ] local__source_data_formatter.inc
            - [ ] local__source_data_widget.inc
            - [ ] local__source_data.inc
        - [ ] Obi__organism
            - [ ] obi__organism_formatter.inc
            - [ ] obi__organism_widget.inc
            - [ ] obi__organism.inc
        - [ ] Ogi__location_on_map
            - [ ] ogi__location_on_map_formatter.inc
            - [ ] ogi__location_on_map_widget.inc
            - [ ] ogi__location_on_map.inc
        - [ ] Operation__analysis
            - [ ] operation__analysis_formatter.inc
            - [ ] operation__analysis_widget.inc
            - [ ] operation__analysis.inc
        - [ ] operation__phylotree_vis
            - [ ] operation__phylotree_vis_formatter.inc
            - [ ] operation__phylotree_vis_widget.inc
            - [ ] Operation__phylotree_vis.inc
        - [ ] Sbo__database_cross_reference
            - [ ] sbo__database_cross_reference_formatter.inc
            - [ ] sbo__database_cross_reference_widget.inc
            - [ ] sbo__database_cross_reference.inc
        - [ ] Sbo__phenotype
            - [ ] sbo__phenotype_formatter.inc
            - [ ] sbo__phenotype_widget.inc
            - [ ] sbo__phenotype.inc
        - [ ] sbo__relationship
            - [ ] sbo__relationship_formatter.inc
            - [ ] sbo__relationship_widget.inc
            - [ ] sbo__relationship.inc
        - [ ] sbo__relationship_table
            - [ ] sbo__relationship_table_formatter.inc
        - [ ] schema__additional_type
            - [ ] schema__additional_type_formatter.inc
            - [ ] schema__additional_type_widget.inc
            - [ ] schema__additional_type.inc
        - [ ] schema__alternate_name
            - [ ] schema__alternate_name_formatter.inc
            - [ ] schema__alternate_name_widget.inc
            - [ ] schema__alternate_name.inc
        - [ ] schema__publication
            - [ ] schema__publication_formatter.inc
            - [ ] schema__publication_widget.inc
            - [ ] schema__publication.inc
        - [ ] sep__protocol
            - [ ] sep__protocol_formatter.inc
            - [ ] sep__protocol_widget.inc
            - [ ] Sep__protocol.inc
        - [ ] sio__annotation
            - [ ] sio__annotation_formatter.inc
            - [ ] sio__annotation_widget.inc
            - [ ] Sio__annotation.inc
        - [ ] Sio__references
            - [ ] sio__references_formatter.inc
            - [ ] sio__references_widget.inc
            - [ ] sio__references.inc
        - [ ] sio__vocabulary
            - [ ] sio__vocabulary_formatter.inc
            - [ ] sio__vocabulary_widget.inc
            - [ ] Sio__vocabulary.inc
        - [ ] so__cds
            - [ ] so__cds_formatter.inc
            - [ ] so__cds_widget.inc
            - [ ] So__cds.inc
        - [ ] So__genotype
            - [ ] so__genotype_formatter.inc
            - [ ] so__genotype_widget.inc
            - [ ] so__genotype.inc
        - [ ] so__transcript
            - [ ] so__transcript_formatter.inc
            - [ ] so__transcript_widget.inc
            - [ ] So__transcript.inc
        - [ ] taxrank__infraspecific_taxon
            - [ ] taxrank__infraspecific_taxon_formatter.inc
            - [ ] taxrank__infraspecific_taxon_widget.inc
            - [ ] Taxrank__infraspecific_taxon.inc
        - [ ] uo__unit
            - [ ] uo__unit_formatter.inc
            - [ ] uo__unit_widget.inc
            - [ ] uo__unit.inc

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
