### ISSUE TITLE
Group 1: Upgrade Permissions (only checking needed)

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#20]
I believe this is complete and stored in the tripal.permissions.yml file: All that is needed is double checking. This is a great opportunity to familiarize yourself with permissions in Drupal 8!

Resources:
- [hook_permissions in Tripal 3](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/tripal.module#L708-L786)
- [Drupal 8 changelog](https://www.drupal.org/node/2311427)
- [Drupal 8 Permissions tutorial](https://benmarshall.me/drupal-8-module-permissions/)

**Comment by srobb1** [comment]
I think I understand, and I searched for each of the permission types in 7.x-3.x in the t4d8 tripal.permissions.yml file.

I found most of the T3 permissions described in T4D8, but not all. See tables below for more detail and notes. In summary, we are missing uploading, importers, publishing, and "view/dev/helps" permissions.

When you check out these tables, it should be clear if I am understanding this check or if I am totally lost. Let me know. Also, if my notes are confusing, I should be able to explain myself in a different way.

Permission types in this table ordered by line in https://github.com/tripal/tripal/blob/7.x-3.x/tripal/tripal.module#L708-L786

Each permission   type in 7.x-3.x | t4d8: tripal.permissions.yml
-- | --
L#713   'administer tripal' => array( | FOUND
L#718 'access   tripal content overview' => array( | FOUND
L#723    'manage tripal content types' => array( | FOUND
L#728 'publish   tripal content' => array( | NONE: I can find permission types for adding content but not publishing   content
L#733    'upload files' => array( | NONE: nothing about uploading files
L#737 'view   dev helps' => array( | NONE: nothing about view dev help
L#750    foreach ($bundles as $bundle) {$permissions['view ' .   $bundle->name] = array( | FOUND for CV terms and controlled vocab entities
L#754 foreach   ($bundles as $bundle) {$permissions['create ' . $bundle->name] = array( | FOUND for CV terms and controlled vocab entities
L#759 foreach ($bundles as $bundle)   {$permissions['edit ' . $bundle->name] = array( | FOUND for CV terms and controlled vocab entities
L#764 foreach ($bundles as   $bundle) {$permissions['delete ' . $bundle->name] = array( | FOUND for CV terms and controlled vocab entities
L#778 foreach ($importers as $class_name)   { … $permissions['use ' . $machine_name . ' importer'] = array( | NONE: I can't find anything about importers


This table, ordered by permission types found in tripal.permissions.yml (but first column is still T3)


7.x-3.x | t4d8: tripal.permissions.yml | section
-- | -- | --
L#778 foreach ($importers as $class_name)   { … $permissions['use ' . $machine_name . ' importer'] = array( | NONE: I can't find anything about importers |  
L#737 'view   dev helps' => array( | NONE: nothing about view dev help |  
L#733    'upload files' => array( | NONE: nothing about uploading files |  
L#728 'publish   tripal content' => array( | NONE: I can find permission types   for adding content but not publishing content
L#713   'administer tripal' => array( | administer tripal | line1 of tripal.permission.yml
is this 'administer tripal' ?? | administer controlled vocabulary entities | Controlled Vocab Entities
L#754   $permissions['create ' . $bundle->name] = array( | add controlled vocabulary entities | Controlled Vocab Entities
L#759   $permissions['edit ' . $bundle->name] = array( | edit controlled vocabulary entities | Controlled Vocab Entities
L#764 $permissions['delete ' .   $bundle->name] = array( | delete controlled vocabulary entities | Controlled Vocab Entities
L#718 'access   tripal content overview' => array( | access controlled vocabulary overview | Controlled Vocab Entities
L#750    $permissions['view ' . $bundle->name] = array( | view controlled vocabulary entities | Controlled Vocab Entities
is this 'administer tripal' ?? | administer controlled vocabulary term entities | CV Terms
L#754   $permissions['create ' . $bundle->name] = array( | add controlled vocabulary term entities | CV Terms
L#759   $permissions['edit ' . $bundle->name] = array( | edit controlled vocabulary term entities | CV Terms
L#764 $permissions['delete ' .   $bundle->name] = array( | delete controlled vocabulary term entities | CV Terms
L#718 'access   tripal content overview' => array( | access controlled vocabulary term overview | CV Terms
L#750    $permissions['view ' . $bundle->name] = array( | view controlled vocabulary term entities | CV Terms
is this 'administer tripal' ?? | administer tripal content types | Tripal Content Entities
L#723    'manage tripal content types' => array( | add tripal content entities | Tripal Content Entities
L#723    'manage tripal content types' => array( | edit tripal content entities | Tripal Content Entities
L#723    'manage tripal content types' => array( | delete tripal content entities | Tripal Content Entities
L#718 'access   tripal content overview' => array( | access tripal content overview | Tripal Content Entities
None: do not see any corresponding   7.x-3.x to view published/unpublished content | view published tripal content entities | Tripal Content Entities
None: do not see any corresponding   7.x-3.x to view published/unpublished content | view unpublished tripal content entities | Tripal Content Entities

**Comment by laceysanderson** [comment]
Thank you @srobb1!!! 🎉  I've followed up with all of these and everything looks good now
