### ISSUE TITLE
Group 1: HTML5 File Upload Element

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#22]
This issue is to handle upgrading the Tripal HTML5 upload form element used in all Tripal Importers.

Resources:
- [ ] [Implementation in Tripal 3](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/tripal.module#L1398-L1568)
- [ ] [hook_element_info is replaced by class](https://www.drupal.org/node/2320115)

**Comment by par12005** [comment]
@laceysanderson, I've submitted PR #44 which upgrades the HTML5 File Upload form element to Drupal 8.

**Comment by laceysanderson** [comment]
Merged 👍  Thank you for the contribution!
