### ISSUE TITLE
Chado API functions need a ChadoConnection argument

### ISSUE THREAD

**Issue by spficklin** [tripal/t4d8#225]
In the process of reviewing PR #209. I realized that our current prepare code can only prepare the default Chado. If you have a second Chado instance it will still only prepare the default Chado.  The problem is that it's using some old API functions that have been ported to Drupal 9.  These functions can only work with the default Chado installation.  

We have 2 options:
1.  Add a new argument to all of our Chado API functions to pass in the ChadoConnection instance we want them to use 
2. Create new services to replace those APIs (e.g. Custom Tables).

For the sake of time, I'm going to add an optional argument to the end of the Chado API functions arguments as I use them.  This will ensure they stay backwards compatible but should allow for any ChadoConnection to be used.  In the long-term we want to replace them with services.

**Comment by laceysanderson** [comment]
Closing as we are deprecating those api functions now
