### ISSUE TITLE
Group 1: FORMS Tripal File Management forms

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#23]
In Tripal 3 we have a file management system for users. This issue is to upgrade the administration forms for this file management system. Specifically,

See`admin/tripal/files` and sub-pages on your Tripal3 site.
![Screen Shot 2020-01-05 at 9 29 19 PM](https://user-images.githubusercontent.com/1566301/71793459-89e86c80-3002-11ea-9e27-e9037ff97311.png)
![Screen Shot 2020-01-05 at 9 29 29 PM](https://user-images.githubusercontent.com/1566301/71793458-89e86c80-3002-11ea-82bb-12768c22d50b.png)
![Screen Shot 2020-01-05 at 9 32 54 PM](https://user-images.githubusercontent.com/1566301/71793551-ecda0380-3002-11ea-8dcd-72e671165d70.png)

![Screen Shot 2020-01-05 at 9 29 47 PM](https://user-images.githubusercontent.com/1566301/71793457-89e86c80-3002-11ea-80a7-82d914d2ce7d.png)

Resources:
- [Tripal 3 implementation](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.admin_files.inc)
- [Drupal Form API](https://www.drupal.org/docs/8/api/form-api/introduction-to-form-api)
- [How to upgrade forms to Drupal 8](https://www.drupal.org/node/1932058)

**Comment by almasaeed2010** [comment]
I am gonna attempt to get this done

**Comment by almasaeed2010** [comment]
PR submitted #31

**Comment by almasaeed2010** [comment]
This has been merged but there is a remaining issue with the "edit" and "remove" links not rendering correctly. 

<img width="855" alt="Screen Shot 2020-01-17 at 8 36 40 AM" src="https://user-images.githubusercontent.com/1512664/72616299-9d4dde80-3904-11ea-9125-2d25b91161f3.png">

**Comment by laceysanderson** [comment]
Fixed in the most recent commit using render arrays.
![Screen Shot 2020-01-17 at 3 05 26 PM](https://user-images.githubusercontent.com/1566301/72646060-c9845200-393a-11ea-82fd-e25b255f4acc.png)

**Comment by laceysanderson** [comment]
This was completed
