### ISSUE TITLE
Group 1: FORMS Registration Form

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#24]
In Tripal 3 we have a registration form for administrators to register with tripal.info. This is important for ongoing funding and presentations. This issue is to upgrade the Site Registration form shown below to Drupal 8:
![Firefox_Screenshot_2020-01-06T18-17-08 386Z](https://user-images.githubusercontent.com/1566301/71838460-78dd4100-307e-11ea-9698-400f1f5a0ed5.png)

Resources:
- [Tripal 3 implementation](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.registration.inc)
- [Drupal Form API](https://www.drupal.org/docs/8/api/form-api/introduction-to-form-api)
- [How to upgrade forms to Drupal 8](https://www.drupal.org/node/1932058)

**Comment by risharde** [comment]
I'll try my best to convert this from D7 to D8

**Comment by risharde** [comment]
I'm trying my very best to get this converted @laceysanderson

**Comment by risharde** [comment]
https://github.com/tripal/t4d8/pull/30 @laceysanderson 

My apologies, this is as much as I can do at the moment due to my inexperience with D8, the PR shows what still needs to be done like form_state and multiple fund sources button

**Comment by laceysanderson** [comment]
Awesome! Thanks for getting us started :-) I'll take a look at it right away

**Comment by laceysanderson** [comment]
I've committed your PR (#30) into `d8-tv4-issue24-registrationform` branch to provide a great base for future work on this issue. Thank you!

**Comment by katherynbuble** [comment]
Planning to work on this tomorrow (Jan 10, 2020).

**Comment by risharde** [comment]
Thank you @katherynbuble ! Really appreciate you continuing this!

**Comment by par12005** [comment]
@laceysanderson, I just submitted a PR for my attempt at implementing the submission/validation functions for the registration form.

Also, I'm new to both Tripal 4 and Drupal 8, so if my code has any issues related to the differences between T3/4 or D7/8, please let me know, I would love to learn more about both!

**Comment by par12005** [comment]
Thanks @laceysanderson for merging my PR! Do you think the branch `d8-tv4-issue24-registrationform` is ready to be merged into `8.x-4.x`?

**Comment by laceysanderson** [comment]
I guess we could. I was going to wait until tripal/tripal#1329 was fixed but that could be done after as well. It is completely functional after all 😃 👍

**Comment by laceysanderson** [comment]
Thank you everyone for your contributions!!! The registration form has been merged back into `8.x-4.x` and works! The only think left to be completed is tripal/tripal#1329 which will be carried on in that issue.

**Comment by par12005** [comment]
Thanks @laceysanderson!
