### ISSUE TITLE
Group 1: API Vocab/Terms api

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#26]
This issue is specifically to upgrade [tripal/tripal/api/tripal.terms.api.inc](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/api/tripal.terms.api.inc). **To take on upgrade of one of these functions just comment below with the function you would like to take on.**

- [ ] Hooks near the top of the file
- [ ] tripal_add_term()  **[Good first task]**
- [x] tripal_get_term_details() **[Good first task]**
- [ ] tripal_get_vocabulary_root_terms()
- [ ] tripal_get_term_children()
- [ ] tripal_get_vocabulary_details() **[Good first task]**
- [ ] tripal_get_vocabulary_terms() **[Good first task]**
- [ ] tripal_get_vocabularies() **[Good first task]**
- [ ] tripal_get_term_lookup_form() and tripal_get_term_lookup_form_result() **[Good first task]**

Resources:
- [Hands-On Training: Controlled Vocabulary Terms Create/Load](https://tripal4.readthedocs.io/en/latest/dev_guide/lessons/create_cvterms.html)
- [Drupal Form API](https://www.drupal.org/docs/8/api/form-api/introduction-to-form-api)
- [How to upgrade forms to Drupal 8](https://www.drupal.org/node/1932058)

**Comment by spficklin** [comment]
I'll start working on these.

**Comment by laceysanderson** [comment]
Completed `tripal_get_term_details()` in branch `28-tv4-tripalFields`
