### ISSUE TITLE
Drupal 10 Compatibility

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#263]
We are not yet Drupal 10 compatible and this issue creates a place to work on that :-)

Please add more testing to functionality that you are working on to make these version upgrades easier!
Even simply calling your methods and only asserting the return value is EXTREMELY HELPFUL as it will ensure most of our code is checked for deprecation notices which greatly reduces the amount of work needed when those deprecation notices are finally removed ;-)

**Comment by spficklin** [comment]
Just curious, do we have code on a 10.x-4.x branch that we need to maintain as well?

**Comment by laceysanderson** [comment]
No, everything is still on the 9.x-4.x.

I think when we move this back to the core Tripal repo we need to change our main branch naming to not include the Drupal version in response to the change in Drupal philosophy. What do you think @spficklin?

Drupal is using the naming `9.3.x-dev` for their branch names so I'm thinking our main branch should be `4.x-dev` to match that convention. In the future I think we would only do a major version shift if there is a large change in infrastructure (i.e. if we decide to move to microservices) and that should no longer include Drupal version changes 🎉 . What do you think? (Question open to entire community as always :-) but especially to the @tripal/project-managent-commitee-pmc)

**Comment by spficklin** [comment]
Okay. That makes sense and seems to be what is recommended by Drupal too:  https://www.drupal.org/docs/develop/git/git-for-drupal-project-maintainers/release-naming-conventions

**Comment by laceysanderson** [comment]
I noticed in that doc that they dropped the `-dev` off the branch. I was going based on [packagist/drupal/core](https://packagist.org/packages/drupal/core) but I just confirmed in the [source](https://git.drupalcode.org/project/drupal/-/branches) that they use `9.3.x` which matches the doc you linked @spficklin and the dev is added when a nightly development release is created.

**As such, our new core branch will be `4.x` to match Drupal core and naming Drupal conventions** :-)
