### ISSUE TITLE
Group 1: API Entities api

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#27]
This issue is specifically to upgrade [tripal/tripal/api/tripal.entities.api.inc](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/api/tripal.entities.api.inc). **To take on upgrade of one of these functions just comment below with the function you would like to take on.**

- [ ] Hooks at the beginning of the file and tripal_tripal_cron_notification()
- [ ] tripal_load_entity() **[Good first task]**
- [ ] tripal_load_term_entity() **[Good first task]**
- [ ] tripal_load_vocab_entity() **[Good first task]**
- [ ] tripal_load_bundle_entity() **[Good first task]**
- [ ] tripal_add_notification()
- [ ] tripal_create_bundle() **[Good first task]**
- [ ] tripal_get_content_types() **[Good first task]**
- [ ] tripal_get_content_type() **[Good first task]**
- [ ] tripal_create_bundle_fields() *~Hold off until fields are upgraded*
- [ ] tripal_update_bundle_field() *~Hold off until fields are upgraded*
- [ ] tripal_get_bundle_variable() *~Hold off until fields are upgraded*
- [ ] tripal_set_bundle_variable() *~Hold off until fields are upgraded*
- [ ] tripal_get_title_format() *~Hold off until fields are upgraded*
- [ ] tripal_get_default_title_format() *~Hold off until fields are upgraded*
- [ ] tripal_get_entity_tokens() *~Hold off until fields are upgraded*
- [ ] tripal_replace_entity_tokens() *~Hold off until fields are upgraded*
- [ ] tripal_entity_label() **[Good first task]**
- [ ] tripal_get_bundle_details() **[Good first task]**
- [ ] tripal_insert_entity() **[Good first task]**
- [ ] tripal_unpublish_orphans()

Resources:
- [Hands-On Training: Controlled Vocabulary Terms Create/Load](https://tripal4.readthedocs.io/en/latest/dev_guide/lessons/create_cvterms.html)

**Comment by Ferrisx4** [comment]
Tackling a few of these, starting with tripal_load_entity()

**Comment by laceysanderson** [comment]
For working on tripal_get_content_types(). Here is the function in Tripal3: https://github.com/tripal/tripal/blob/7.x-3.x/tripal/api/tripal.entities.api.inc#L612

To do this you are going to want to work with the entity query api: https://api.drupal.org/api/drupal/core!lib!Drupal.php/function/Drupal%3A%3AentityQuery/8.2.x for the [TripalEntityType](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal/src/Entity/TripalEntityType.php). If you look in the linked class you get an idea of what methods are available to access information.

**Comment by laceysanderson** [comment]
Just checking in on the progress on this. @Ferrisx4 are all your changes in https://github.com/tripal/t4d8/compare/27-EntitiesAPI? @ksbuble were you able to make any progress on this issue? Also, are either of you available to continue this work?

**Comment by Ferrisx4** [comment]
@laceysanderson Hi, yes all my cofest work was in this section. I have been continuing my work, `tripal_load_vocab_entity()` and `tripal_load_term_entity()` are basically done. Still working on them one by one.

**Comment by Ferrisx4** [comment]
Current work in old branch 27-EntitiesAPI is here:
[27-EntitiesAPI.patch.txt](https://github.com/tripal/t4d8/files/8188693/27-EntitiesAPI.patch.txt)

Closing the branch due to inactivity and staleness.

**Comment by laceysanderson** [comment]
Upgrading this API is not a priority as it's not needed for the new functionality. Instead if this is updated it would be in the legacy api module.

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
