### ISSUE TITLE
Group 1: TripalField

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#28]
This issue deals with updating the TripalField infrastructure. The hope is to do this such that minimal to no work needs to be done on contributed fields. Specifically, these are the files being updated:

- [ ] TripalField
  - [ ] Tripalfields
  - [ ] TripalField.inc
  - [ ] TripalFieldFormatter.inc
  - [ ] TripalFieldWidget.inc
  - [ ] CONTENT_TYPE
    - [ ] content_type.inc
  - [ ] RDFS__TYPE
    - [ ] rdfs__type_formatter.inc
    - [ ] rdfs__type_widget.inc
    - [ ] Rdfs__type.inc
  - [ ] TripalFieldDownloaders
    - [ ] TripalCSVDownloader.inc
    - [ ] TripalFieldDownloader.inc
    - [ ] TripalGFF3Downloader.inc
    - [ ] TripalNucFASTADownloader.inc
    - [ ] TripalProteinFASTADownloader.inc
    - [ ] TripalTabDownloader.inc

**Comment by laceysanderson** [comment]
This needs to wait until the chado api is updated.

**Comment by spficklin** [comment]
Since this is closely tied to #26 I'm going to tackle this one as well.

**Comment by laceysanderson** [comment]
This was the state of this work on Sept 24 as of PR #65 

> Merging in the current state or fields. What has been done?
> Currently there are two functional fields:
> 
>    - RDFSType: just shows the content type as a field.
>    - OBIOrganism: FK organism
> 
> For the OBIOrganism field, it currently stores the values in the Drupal Cache, is completely configurable and pulls options from chado. It cannot write a new FK Record to chado yet (e.g. a feature) because the rest of the fields for that table are needed yet.
> 
> Additionally, it is not multi-chado compatible yet and the upgrade to the chado query API is not complete yet.

Chado API is now updated and Tripal Vocabularies are fully tied to chado. Ready to move forward on this again 🎉

**Comment by 4ctrl-alt-del** [comment]
Moved to #129. Created new issue to track progress for Tripal Fields because I am starting fresh from the beginning.

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
