### ISSUE TITLE
Vocabularies did not appear in the Tripal tool bar after I finished install Tripal in Drupal guided by Docs

### ISSUE THREAD

**Issue by Xueliang24** [tripal/t4d8#285]
I used git clone t4b8 repository in my web/modules and when I entered the website,  Vocabularies did not appear![Figures](https://upload-images.jianshu.io/upload_images/12888637-7abb767260cadbc2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240). I have tried to install it tiwce, 
Could you give me some help? somthing errors happend in Tripal -> more -> Tripal Content Terms.
May I choose  to intall Tripal v3 guided by Tripal v3 docs

**Comment by spficklin** [comment]
Hi @Xueliang24 what specifically are you looking for?  For the OBO (vocabulary) Importer?

**Comment by Xueliang24** [comment]
Yeah, when I read the guidelines, I missed it. Maybe, I need to learn more OBO knowledges @spficklin

**Comment by spficklin** [comment]
Was there anything else related to vocabularies you were looking for?  

We do have the OBO loader working in Tripal v4. It can be found by clicking on "Data Loaders".  If you have the most recent clone of the 9.x-4.x branch it has both the OBO and GFF3 loaders.   But before you install any vocabularies you will want to install and prepare Chado. You can find both of those by clickin on the "Chado" link you show in the screenshot.

**Comment by Xueliang24** [comment]
> Was there anything else related to vocabularies you were looking for?
> 
> We do have the OBO loader working in Tripal v4. It can be found by clicking on "Data Loaders". If you have the most recent clone of the 9.x-4.x branch it has both the OBO and GFF3 loaders. But before you install any vocabularies you will want to install and prepare Chado. You can find both of those by clickin on the "Chado" link you show in the screenshot.

I thought Tripal v4 was like Tripal v3 which made me confused about the problem above. Now I know I need learn more. 
Thanks for your warm answer

**Comment by spficklin** [comment]
@Xueliang24 unforutnately, the documentation for Tripal4 isn't quite yet up to par.  We hope to have an alpha release before the end of the year with improved documentation.

**Comment by Xueliang24** [comment]
I am so sorry open this issue again. I tried to accomplish the flow (from install drupal to tripal) again. After I installed Drupal, I want to install the Tripal. I followed the steps from guidelines:
>1.install Drupal
2.Clone this repository in your web/modules directory.
3.Enable Tripal in your site using the Administration Toolbar > Extend
4.Use drush to rebuild the cache (drush cache-rebuild) so Tripal menu items appear correctly.

I  tried step 4 then installed Tripal in the Extend in the web interface or I also firstly installed the Tripal in the extend in the web interface then step 4. They were failed.  This led to the error of install Chado. Besides, I couldn't uninstall the Tripal Extend. Or It was failed that reinstall Tripal for devel. 
The information was `Error: Unable to determine Drupal's schema name..`.
The web error only told `The website encountered an unexpected error. Please try again later.`. @spficklin

**Comment by Xueliang24** [comment]
I also tried to install tripal by docker. emm... It also told me that The website encountered an unexpected error. Please try again later. May be I need know what happened by Xdebug

**Comment by laceysanderson** [comment]
Sorry this was an outdated part of the tutorial and has been removed.
