### ISSUE TITLE
Group 3: Updates to Job Management

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#3]
Please tag all tickets and pr's with group 3 to denote it relates to this group of updates.

Files this update will require to be reviewed and updated (in order):

- [x] Tripal Module
   - [x] tripal.jobs.api.inc
   - [x] TripalJob.inc   
   - [x] tripal.jobs.inc 
   - [x] Jobs admin views
   - [x] tripal.notice.api.inc
   - [x] drush commands

**Comment by spficklin** [comment]
I'm going to start the Tripal Jobs conversion.  For the alpha  release.  This will not include the TripalDaemon (that will be done later).

**Comment by spficklin** [comment]
The branch used for this work is named `3-tv4-jobs`

**Comment by spficklin** [comment]
I removed the TripalDaemon from this item and created a new issue for it. #68

**Comment by laceysanderson** [comment]
Work is merged! Thank you @spficklin 🎉
