### ISSUE TITLE
Updates to Data Importing

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#4]
Please tag all tickets and pr's with group 4 to denote it relates to this group of updates.

Files this update will require to be reviewed and updated (in order):

- [ ] Tripal Bulk Loader Module
    - [ ] Convert tripal_bulk_loader.info to tripal_bulk_loader.yml
        - [ ]  tripal_bulk_loader.module
    - [ ] Convert hook_menu and forms
    - [ ] Convert D7 variables to D8 Config
    - [ ] Convert D7 variables to D8’s state system
    - [ ] api
        - [ ] tripal_bulk_loader.api.templates.inc
        - [ ] tripal_bulk_loader.DEPRECATED.inc
    - [ ] includes
        - [ ] tripal_bulk_loader.admin.inc
        - [ ] tripal_bulk_loader.admin.templates.inc
        - [ ] tripal_bulk_loader.chado_node.inc
        - [ ] tripal_bulk_loader.constants.inc
        - [ ] Tripal_bulk_loader.loader.inc
- [ ] Tripal Module
    - [ ] includes
        - [ ] tripal.importer.inc
        - [ ] TripalImporter.inc
        - [ ] tripal.upload.inc
    - [ ] api
        - [ ] tripal.importer.api.inc
        - [ ] tripal.upload.api.inc
- [ ] Tripal Chado Module
    - [ ] includes
        - [ ] Tripalimporter
            - [ ] FASTAImporter.inc
            - [ ] GFF3Importer.inc
            - [ ] NewickImporter.inc
            - [ ] OBOImporter.inc
            - [ ] PubBulkImporter.inc
            - [ ] TaxonomyImporter.inc
        - [ ] Exporters
            - [ ] tripal_chado.gff_exporter.inc
            - [ ] tripal_chado.seq_extract.inc
        - [ ] loaders
            - [ ] OWLStanza.inc
            - [ ] tripal_chado.phylotree_newick.inc
            - [ ] tripal_chado.pub_importer_AGL.inc
            - [ ] tripal_chado.pub_importer_PMID.inc
            - [ ] tripal_chado.pub_importers.inc
            - [ ] Tripal_cv.owl_loader.php

**Comment by par12005** [comment]
I updated `includes/tripal.upload.inc` and `api/tripal.upload.api.inc`, now combined into [`tripal/api/tripal.upload.api.php`](https://github.com/tripal/t4d8/pull/44/files?file-filters%5B%5D=.php#diff-96354170b78742ae7641166b5f79b5c9), in PR #44, since the upload API needed to be upgraded in order for the HTML5 file upload field to function properly.

**Comment by spficklin** [comment]
Should we move the Tripal bulk loader outside of Core Tripal and make it an extension module?

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
