### ISSUE TITLE
Updates to Views

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#5]
Please tag all tickets and pr's with group 5 to denote it relates to this group of updates.

Files this update will require to be reviewed and updated (in order):

- [ ] Tripal Module
    - [ ] tripal_views_query.inc
    - [ ] tripal.views_default.inc
    - [ ] tripal.views.inc
    - [ ] Views_handlers
        - [ ] tripal_views_handler_area_collections.inc
        - [ ] tripal_views_handler_field_boolean.inc
        - [ ] tripal_views_handler_field_element.inc
        - [ ] tripal_views_handler_field_entity_link_delete.inc
        - [ ] tripal_views_handler_field_entity_link_edit.inc
        - [ ] tripal_views_handler_field_entity_link.inc
        - [ ] tripal_views_handler_field_entity.inc
        - [ ] tripal_views_handler_field_image.inc
        - [ ] tripal_views_handler_field.inc
        - [ ] tripal_views_handler_filter_boolean_operator.inc
        - [ ] tripal_views_handler_filter_element_string.inc
        - [ ] tripal_views_handler_filter_entity_string.inc
        - [ ] tripal_views_handler_filter_numeric.inc
        - [ ] tripal_views_handler_filter_select_string.inc
        - [ ] tripal_views_handler_filter_string.inc
        - [ ] tripal_views_handler_filter.inc
        - [ ] tripal_views_handler_sort_entity_string.inc
        - [ ] tripal_views_handler_sort.inc
- [ ] Tripal Bulk Loader Module
    - [ ] tripal_bulk_loader.views_default.inc
    - [ ] Tripal_bulk_loader.views.inc
- [ ] Tripal Chado Module
    - [ ] tripal_chado.views_default.inc
    - [ ] tripal_chado.views.inc
- [ ] Tripal Chado Views Module
    - [ ] Convert tripal_chado_views.info to tripal_chado_views.yml
        - [ ]  tripal_chado_views.module
    - [ ] Convert hook_menu and forms
    - [ ] Convert D7 variables to D8 Config
    - [ ] Convert D7 variables to D8’s state system
    - [ ] tripal_chado_views.views_default.inc
    - [ ] tripal_chado_views.views.inc
    - [ ] tripal_views_integration_fields_form.tpl.php
    - [ ] api
        - [ ] tripal_chado_views.api.inc
        - [ ] tripal_chado_views.DEPRECATED.inc
    - [ ] Includes
        - [ ] tripal_chado_views_integration_port.inc
        - [ ] tripal_chado_views_integration_UI.inc
        - [ ] tripal_chado_views_integration.inc
    - [ ] views
        - [ ] handlers
            - [ ] tripal_views_handler_area_action_links.inc
            - [ ] tripal_views_handler_field_sequence.inc
            - [ ] tripal_views_handler_filter_file_upload.inc
            - [ ] tripal_views_handler_filter_no_results.inc
            - [ ] tripal_views_handler_filter_select_cvterm.inc
            - [ ] tripal_views_handler_filter_select_id.inc
            - [ ] tripal_views_handler_filter_select_string.inc
            - [ ] tripal_views_handler_filter_sequence.inc
            - [ ] Tripal_views_handler_filter_textarea.inc
    - [ ] Views-sql-compliant-three-tier-naming-1971160-30.patch

**Comment by laceysanderson** [comment]
The Tripal Jobs listing using a Drupal 8 View. Use this for reference.

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
