### ISSUE TITLE
Group 2: Chado Custom Tables API

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#51]
This issue refers to upgrade of [tripal_chado.api.inc](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/api/tripal_chado.api.inc) **To take on upgrade of one of these functions just comment below with the function you would like to take on.**

- [ ] chado_edit_custom_table() **[Good first task]**
- [ ] chado_create_custom_table() **[Good first task]**
- [ ] chado_validate_custom_table_schema() **[Good first task]**
- [ ] chado_get_custom_table_id() **[Good first task]**
- [ ] chado_get_custom_table_names() **[Good first task]**
- [ ] chado_delete_custom_table() **[Good first task]**

**Comment by Ferrisx4** [comment]
I'll be tackling `chado_edit_custom_table()`, `chado_create_custom_table()`, `chado_validate_custom_table_schema` for now, and the rest shortly after.

**Comment by swapniljha001** [comment]
What does one have to do to resolve this issue?

**Comment by Ferrisx4** [comment]
hi @swapniljha001. I have finished about 75% of the custom table functions and should have a PR ready soon for this.

**Comment by Ferrisx4** [comment]
[Main commit](https://github.com/tripal/t4d8/commit/3fe1016f7637baaf11f5d831a76bc2c4ed3106b4) for this API. Currently testing, will issue PR soon.

**Comment by laceysanderson** [comment]
Completed
