### ISSUE TITLE
Tripal Content Type Machine Name Bugs

### ISSUE THREAD

**Issue by par12005** [tripal/t4d8#53]
Setting a custom machine name for Tripal Content Types that does not abide by the `bio_data_n` convention seems to be causing some issues.

For example, I had two Tripal content types on my dev site. The first was the "Gene" content type, and I allowed it to use the default `bio_data_1` machine name. The second content type was the "Test Type" content type, and I set a custom machine name of `bio_data_12`.

Now I'm going to create a new content type, called "Test Type breaking". The default machine name works as expected, and shows me `bio_data_13`. I changed the machine name to `tripal_content_test_type` and created my breaking content type. This seems to cause two issues:

1. The default bio_data_N number no longer works for Tripal content type machine names. If I now click "Add Tripal Content Type" from the admin > structure > Tripal Content Types page, the default machine name now reads `bio_data_1`. If I proceed with this machine name, I get an exception:
```Drupal\Core\Entity\EntityStorageException: 'tripal_entity_type' entity with ID 'bio_data_1' already exists.```
2. The machine name of my "Test Type breaking" content type displays differently in the UI than it is in the database. If I create content with my "Test Type breaking" content type, then the `type` column in my `tripal_entity` table reads `tripal_content_test_type`, as expected. However, if I navigate to admin > structure > Tripal Content Types and click on the "Test Type breaking" type, it says the machine name is `bio_data_13`, which was the default machine name I saw when I was first filling out the add new content type form. This problem also seems to apply to the "Test Type" content type, which has a machine name of `bio_data_12`, but the one displayed in the UI is `bio_data_2`, which was the default in the add new content type form.

Perhaps users should not be allowed to create custom machine names for Tripal Content types? Or something should be done about the way that the default machine names are handled. My guess is that this is a problem in the `tripal/src/Form/TripalEntityTypeForm.php` file.

**Comment by laceysanderson** [comment]
Thanks for pointing this out! I've added a PR to disable changing the machine name. I choose this route since I believe many Tripal3 extension modules including Tripal core may have made assumptions about this name as it cannot be changed in Tripal3. If you could find time to review that PR I would greatly appreciate it!

**Comment by laceysanderson** [comment]
PR Merged 👍

**Comment by par12005** [comment]
Thanks @laceysanderson!
