### ISSUE TITLE
CV Term accessions

### ISSUE THREAD

**Issue by spficklin** [tripal/t4d8#60]
When adding a controlled vocabulary to Tripal for content types, it automatically adds the short name as the prefix to any accession.  For some vocabularies, such as EDAM, the short name can vary so automatically adding the short name will be incorrect for those types of vocabularies.

**Comment by laceysanderson** [comment]
Proposition:
If we have a TripalVocab object for each namespace in a vocabulary (i.e. EDAM:data and EDAM:format would be separate vocabulary objects) then we can attach each TripalVocab object to both a cv and db in Chado effectively getting rid of the need for the db2cv materialized view. I feel this will be more performant and intuitive and make look-up easier.

**Comment by laceysanderson** [comment]
The "short_name" is actually the IDspace and needs to be updated to be such. https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.1.6

**Comment by laceysanderson** [comment]
Ok after an awesome discussion with @spficklin, here is the current plan:

We are going to have 3 classes:
 - TripalVocab is the namespace/vocabulary
 - TripalVocabSpace is the IDSpace. It points to an originator TripalVocab and then can also point to multiple accessory TripalVocabs.
 - TripalTerm is the actual term. It points to a single IDSpace (TripalVocabSpace).

## Typical Term

A typical term: http://www.sequenceontology.org/browser/current_release/term/SO:0000704

### TripalTerm
 - accession: 0000704
 - name: gene
 - IDSpace: points to the following TripalVocabSpace object.
 - definition: A region (or regions) that includes all of the sequence elements necessary to encode a functional transcript. A gene may include regulatory regions, transcribed regions and/or other functional sequence regions.
 - URL: (generated on demand from IDSpace) http://www.sequenceontology.org/browser/current_release/term/SO:0000704

### TripalVocabSpace:
 - IDSpace: SO
 - namespace: points to the following TripalVocab
 - accessoryNamespaces: empty array
 - URLprefix: http://www.sequenceontology.org/browser/current_release/term/{{idspace}}:{{accession}}

### TripalVocab:
 - namespace: sequence
 - name: The Sequence Ontology
 - description: This is the home page of the Sequence Ontology (SO). SO is a collaborative ontology project for the definition of sequence features used in biological sequence annotation. SO was initially developed by the Gene Ontology Consortium.
 - URL: http://www.sequenceontology.org/

# Vocabulary with multiple IDSpaces (e.g. EDAM)

Now let's think about the EDAM vocabulary which has multiple IDspaces. We would have multiple terms (TripalTerm), each attached to a single IDspace (TripalVocabSpace). Each IDSpace references a single namespace (TripalVocab). This results in a single namespace (TripalVocab; EDAM) referenced by multiple IDspaces (TripalVocabSpace; Data, Operation, Format, etc.).

# Vocabulary with borrowed terms

Now lets think about the borrowed term situation. We would have a single term (TripalTerm) attached to a single IDspace (TripalVocabSpace) and included in multiple vocabularies (TripalVocab) with one being the originator namespace and the rest being accessory namespaces.

# Relationships

All the relationships go from Term > IDSpace > Namespace and thus are not circular. When travelling from IDSpace > Namespace we will default to the originator namespace not the accessory ones.

# Chado Integration

 - TripalVocab maps to chado.cv
 - TripalVocabSpace maps to chado.db
 - TripalTerm includes both chado.cvterm and chado.dbxref
 - Chado cannot currently handle borrowed terms. As such Chado only fills the originator namespace and not the accessory ones.

**Comment by laceysanderson** [comment]
PR Merged
