### ISSUE TITLE
Blank page (not WSOD) when adding Tripal Content when no Tripal Content Types exist

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/t4d8#63]
If an admin attempts to add Tripal Content and there have been no Tripal Content types added (with proper CV and CV term), a blank page is displayed. This is in relation to recently merged PR https://github.com/tripal/t4d8/pull/62

**Comment by risharde** [comment]
Crude initial commit for advice/feedback - https://github.com/tripal/t4d8/tree/63-tv4-wsod_addcontent

**Comment by laceysanderson** [comment]
Fixed in PR #92 Thanks @risharde!
