### ISSUE TITLE
Updates to Display

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#7]
Please tag all tickets and pr's with group 7 to denote it relates to this group of updates.

Files this update will require to be reviewed and updated (in order):

- [ ] Tripal DS Module
    - [ ] Convert tripal_ds.info tripal_ds.yml
        - [ ]  tripal_ds.module
    - [ ] Convert hook_menu and forms
    - [ ] Convert D7 variables to D8 Config
    - [ ] Convert D7 variables to D8’s state system
    - [ ] api
        - [ ] tripal_ds.pane.api.inc
    - [ ] includes
        - [ ] tripal_ds.ds.inc
        - [ ] tripal_ds.field_formatter.inc
        - [ ] tripal_ds.field_group.inc
        - [ ] Tripal_ds.inc
    - [ ] Views
        - [ ] tripal_ds.views_default.inc
        - [ ] Tripal_ds.views.inc

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
