### ISSUE TITLE
Create Icons for the Tripal Toolbar!

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#88]
PR #87 added Tripal to the administration toolbar!

However, you'll notice the administrative toolbar typically has really awesome minimalistic icons... and we do not. This Issue is to remind us to make some :-)

Here they are in core: https://api.drupal.org/api/drupal/core%21modules%21toolbar%21css%21toolbar.icons.theme.css/8.2.x
Drupal uses these: https://github.com/ry5n/libricons/tree/master/src
Here is an example: https://git.drupalcode.org/project/devel/-/blob/4.x/src/ToolbarHandler.php#L103
Here is a tutorial on how: https://drupalcommerce.org/blog/10943/how-create-drupal-8-toolbar-icon

<img width="1087" alt="Screen Shot 2021-01-04 at 2 59 04 PM" src="https://user-images.githubusercontent.com/1566301/103579640-41c28b00-4e9e-11eb-829d-4447af5b7656.png">

**Comment by reynoldtan** [comment]
Icon set design no. 1
![icons](https://user-images.githubusercontent.com/15472253/104342615-a2664f00-54c0-11eb-9f08-83f92b2bf36f.jpg)


![icons-h](https://user-images.githubusercontent.com/15472253/104342664-b14d0180-54c0-11eb-8409-a35c5d191463.jpg)

![icons-v](https://user-images.githubusercontent.com/15472253/104342706-b9a53c80-54c0-11eb-9775-b3a260e73544.jpg)

**Comment by laceysanderson** [comment]
Nice! Maybe a little more detail then the other Drupal icons (especially page structure and data import feel a bit cluttered) but overall I like them. @spficklin what do you think?

**Comment by spficklin** [comment]
Yes, I agree. I like them too!
