### ISSUE TITLE
Group 2: Chado Setup/Prepare

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#89]
We need to upgrade the prepare step which happens after chado is installed. 

Tripal 3: https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/setup/tripal_chado.setup.inc

This will include
 - [the simple form](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/setup/tripal_chado.setup.inc#L10)
 - [Creating Tripal Vocabs, etc.](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/setup/tripal_chado.setup.inc#L73) Currently we'll focus only on those needed for content types.
 - [Creating Tripal Content Types which map to the terms](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/setup/tripal_chado.setup.inc#L268-L277).
 - [Materialized Views and custom tables](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/setup/tripal_chado.setup.inc#L214) not needed for alpha release.
 - Semweb will be done in Group 6

Resources:
 - Forms:
    - [Tripal 3 implementation](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.registration.inc)
    - [Drupal Form API](https://www.drupal.org/docs/8/api/form-api/introduction-to-form-api)
    - [How to upgrade forms to Drupal 8](https://www.drupal.org/node/1932058)
- Vocabularies:
    - [Tripal4 Structure](https://tripal4.readthedocs.io/en/latest/dev_guide/cvterms.html)
    - [Tripal4 HowTo](https://tripal4.readthedocs.io/en/latest/dev_guide/lessons/create_cvterms.html)
- Content Types:
    - [Tripal Content Types Class](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal/src/Entity/TripalEntityType.php)

**Comment by laceysanderson** [comment]
Here is the current work on this issue from the Jan 2021 Codefest: https://github.com/tripal/t4d8/compare/9.x-4.x...par12005:89-chadoSetupPrepare 

@par12005 do you think you will have time to complete this soon?

**Comment by par12005** [comment]
@laceysanderson Sorry for the slow response!

I've pushed my changes for this issue and included some notes about what's still missing from the default content types and why in my PR.

**Comment by laceysanderson** [comment]
Great! Thanks @par12005! I'll look at it as soon as I can!

**Comment by risharde** [comment]
Thanks @par12005 , @laceysanderson I tried testing this code but it suffers from the same issue I sent you via Slack so it doesn't seem the error is related to @par12005 code but something else happening related to core branch (9.x-4.x) or my specific environment at the moment (though I have removed the docker and tried redoing everything).

`Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "chado_tripalvocab" does not exist LINE 3: chado_tripalvocab chado_tripalvocab ^: SELECT 1 AS expression FROM {chado_tripalvocab} chado_tripalvocab WHERE tripalvocab_id = :db_condition_placeholder_0; Array ( [:db_condition_placeholder_0] => 1 ) in Drupal\tripal_chado\Plugin\TripalTermStorage\TripalTermStorageChado->postSaveVocab() (line 68 of /var/www/drupal8/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalTermStorage/TripalTermStorageChado.php).`

**Comment by risharde** [comment]
@laceysanderson second test with the docker environment reaches max execution time (30 seconds) when trying to execute via the  jobs UI page. This is just a note during testing and reasonable in case anyone ever tries doing this from UI. I'll be reattempting by running the command line generated for the job once available.

`2021-02-08 20:36:31: Job ID 1. 2021-02-08 20:36:31: Calling: tripal_chado_prepare_chado(chado) Setting Schema to "chado". Loading ontologies...
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/drupal8/vendor/symfony/yaml/Parser.php on line 955`

**Comment by laceysanderson** [comment]
Most of this is complete. Closing this issue as it's not very helpful for finishing the remaining items.
