### ISSUE TITLE
Tv3 Updates Needed in Tv4

### ISSUE THREAD

**Issue by spficklin** [tripal/t4d8#95]
I'm creating this issue as a place where we can add items that were added in Tv3 after we separated this t4d8 repository.   As we review the pull request history for the Tv3 repository we can return here and add check boxes below link to the corresponding pull request.  

- [ ]  The TripalField class got a new theme function for theming of the instance settings form,   (PR coming soon). 
- [ ]  An updated GFF3 Importer, https://github.com/tripal/tripal/pull/1141
- [ ]  Date/Time incorrect time on display, https://github.com/tripal/tripal/pull/1148

**Comment by laceysanderson** [comment]
We didn't keep up with this so it's not as helpful as we had hoped. I will add issues for these specific ones though :-)
